### ISSUE TITLE
Was working until a few days ago

### ISSUE THREAD

**Issue by norrinr** [Liamraystanley/irccloud-uptime#3]
Disconnected. Reconnecting in 30 seconds.

**Comment by sbrydon** [comment]
Have a look at the wss uri your browser client connects to and replace `self.wss` with it

**Comment by norrinr** [comment]
Thank you, sir!

**Comment by sebastius** [comment]
New user for this wonderful idea, but i only get the Disconnected. Reconnecting in 30 seconds. Can't figure out whats wrong.
