### ISSUE TITLE
Disconnected. Reconnecting in 30 seconds.

### ISSUE THREAD

**Issue by sebastius** [Liamraystanley/irccloud-uptime#5]
Sorry to say it's still here. (or back again). Please advise because i really don't get whats wrong.

**Comment by Liamraystanley** [comment]
Please note that this script is unlikely to work anymore due to efforts of the IRCcloud team attempting to prevent scripts like this from functioning.

**Comment by sebastius** [comment]
Ah, makes sense! Thanks for your reply!

Sebastian
